### PR TITLE
Silence warning

### PR DESCRIPTION
**Pull request by joneshf**

### CODE REVIEW

**Comment by nwolverson** [comment]
Uh, so everything from `mkEffFn6` and above was broken?  This one is kind of amusing.

**Comment by joneshf** [comment]
Can you throw a new tag on this?

**Comment by joneshf** [comment]
Tag came out as `v1.3.0-erl2`: https://github.com/purerl/purescript-eff/releases/tag/v1.3.0-erl2

**Comment by nwolverson** [comment]
Thanks, should be fixed now.

**Pull request merged**
